export const LOAD_POLICY_CATEGORIES_LOADING = 'LOAD_POLICY_CATEGORIES_LOADING';
export const LOAD_POLICY_CATEGORIES_SUCCESS = 'LOAD_POLICY_CATEGORIES_SUCCESS';
export const LOAD_POLICY_CATEGORIES_ERROR = 'LOAD_POLICY_CATEGORIES_ERROR';
